//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnimationDataViewer.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AnimationDataViewer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Remove All 的本地化字符串。
        /// </summary>
        internal static string BtnClearAllList {
            get {
                return ResourceManager.GetString("BtnClearAllList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pack 的本地化字符串。
        /// </summary>
        internal static string BtnPacked {
            get {
                return ResourceManager.GetString("BtnPacked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NineSlice 的本地化字符串。
        /// </summary>
        internal static string BtnPackedNineSlice {
            get {
                return ResourceManager.GetString("BtnPackedNineSlice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove Select 的本地化字符串。
        /// </summary>
        internal static string BtnRemoveSelect {
            get {
                return ResourceManager.GetString("BtnRemoveSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UnPack 的本地化字符串。
        /// </summary>
        internal static string BtnUnPack {
            get {
                return ResourceManager.GetString("BtnUnPack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Crop Image 的本地化字符串。
        /// </summary>
        internal static string CheckBoxCropTexture {
            get {
                return ResourceManager.GetString("CheckBoxCropTexture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generate Atlas 的本地化字符串。
        /// </summary>
        internal static string CheckBoxGenerateAtlas {
            get {
                return ResourceManager.GetString("CheckBoxGenerateAtlas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generate Png 的本地化字符串。
        /// </summary>
        internal static string CheckBoxGeneratePng {
            get {
                return ResourceManager.GetString("CheckBoxGeneratePng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Power of 2 的本地化字符串。
        /// </summary>
        internal static string CheckBoxPowersOfTwo {
            get {
                return ResourceManager.GetString("CheckBoxPowersOfTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Atlas File 的本地化字符串。
        /// </summary>
        internal static string LblFilePathAtlas {
            get {
                return ResourceManager.GetString("LblFilePathAtlas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Texture File 的本地化字符串。
        /// </summary>
        internal static string LblFilePathPng {
            get {
                return ResourceManager.GetString("LblFilePathPng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        internal static string MemuAbout {
            get {
                return ResourceManager.GetString("MemuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add File 的本地化字符串。
        /// </summary>
        internal static string MemuAddFile {
            get {
                return ResourceManager.GetString("MemuAddFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Folder 的本地化字符串。
        /// </summary>
        internal static string MemuAddFolder {
            get {
                return ResourceManager.GetString("MemuAddFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File 的本地化字符串。
        /// </summary>
        internal static string MemuFile {
            get {
                return ResourceManager.GetString("MemuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NineSlice 的本地化字符串。
        /// </summary>
        internal static string TabNineSlice {
            get {
                return ResourceManager.GetString("TabNineSlice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Normal 的本地化字符串。
        /// </summary>
        internal static string TabNormal {
            get {
                return ResourceManager.GetString("TabNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select {0} File 的本地化字符串。
        /// </summary>
        internal static string TitleFileSelect {
            get {
                return ResourceManager.GetString("TitleFileSelect", resourceCulture);
            }
        }
    }
}
